### PR TITLE
Tidy up remove logicworks references

### PR DESCRIPTION
**Pull request by PhilDaintree**

### CODE REVIEW

**Comment by rjonesbsink** [comment]
after adding items to cart, go through delivery address and click next, no payment options will come up. I delete items out of cart. try to add new item. still the same no check out button either

**Comment by PhilDaintree** [comment]
You must set the payment options you wish to use in the weShop setup inside webERP

Phil
Phil Daintree
+64 (0)275 567 890

**Comment by rjonesbsink** [comment]
​can more payment options be added, like for COD customer who will pay by
money order or check or cash when they pick up. and i see there is no
shipping method customer can choose from​

**Comment by webERP-team** [comment]
Yes you can any other payment methods you like with some programming.
Payment by cheque on delivery us already an option

Phil
Phil Daintree
+64 (0)275 567 890

**Comment by rjonesbsink** [comment]
I have turned on bank transfer and still don't see the payment options
listed in webshop. Must be doing something wrong

**Pull request merged**
